#!/usr/bin/env bash
. "$(dirname -- "$0")/_/husky.sh"

BRANCH_NAME="$(git rev-parse --abbrev-ref HEAD)"

if [ "$BRANCH_NAME" = "main" ] || [ "$BRANCH_NAME" = "dev" ]; then
    echo "You are on the wrong branch! All development should be done on feature branches"
    exit 1
fi

npx lint-staged
npm test
